# Generated by Django 5.2.8 on 2025-11-30 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('current_situation', models.CharField(choices=[('employed', 'En emploi (CDI/CDD)'), ('freelance', 'Freelance / Auto-entrepreneur'), ('student', 'Étudiant(e)'), ('seeking', 'En recherche active'), ('other', 'Autre')], max_length=50)),
                ('contract_types', models.JSONField(default=list)),
                ('availability', models.CharField(choices=[('immediate', 'Immédiate'), ('week', 'Sous 1 semaine'), ('twoweeks', 'Sous 2 semaines'), ('month', 'Sous 1 mois'), ('later', 'Plus tard (préciser)')], max_length=50)),
                ('availability_details', models.TextField(blank=True, null=True)),
                ('full_time_flexibility', models.CharField(choices=[('yes', 'Oui, totalement'), ('conditions', 'Oui, mais sous conditions (préciser)'), ('no', 'Non, uniquement temps partiel')], max_length=50)),
                ('full_time_conditions', models.TextField(blank=True, null=True)),
                ('weekly_hours', models.CharField(choices=[('20-25', '20-25h'), ('25-30', '25-30h'), ('30-35', '30-35h'), ('35-40', '35-40h'), ('40+', '40h et plus')], max_length=20)),
                ('time_slots', models.JSONField(default=list)),
                ('week_days', models.JSONField(default=list)),
                ('week_days_details', models.TextField(blank=True, null=True)),
                ('work_mode', models.CharField(choices=[('remote', '100% télétravail'), ('office', '100% sur site'), ('hybrid', 'Hybride'), ('flexible', 'Flexible / Indifférent')], max_length=50)),
                ('personal_constraints', models.TextField(blank=True, null=True)),
                ('languages', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LanguageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('native', 'Langue maternelle'), ('fluent', 'Courant (C1-C2)'), ('professional', 'Professionnel (B2)'), ('intermediate', 'Intermédiaire (B1)'), ('basic', 'Notions (A1-A2)')], max_length=50)),
                ('oral_level', models.CharField(choices=[('very_comfortable', "Très à l'aise"), ('comfortable', "À l'aise"), ('moderate', "Moyennement à l'aise"), ('difficult', 'Avec difficulté')], max_length=50)),
                ('written_level', models.CharField(choices=[('very_comfortable', "Très à l'aise"), ('comfortable', "À l'aise"), ('moderate', "Moyennement à l'aise"), ('difficult', 'Avec difficulté')], max_length=50)),
                ('phone_experience', models.CharField(choices=[('yes_often', 'Oui, régulièrement'), ('yes_occasionally', 'Oui, occasionnellement'), ('no_but_confident', "Non, mais je suis à l'aise"), ('no_concerns', "Non, et j'ai quelques appréhensions")], max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_details', to='resumemanager.application')),
            ],
            options={
                'unique_together': {('application', 'language')},
            },
        ),
    ]
