# Generated by Django 5.2.8 on 2025-11-30 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumemanager', '0002_application_accept_variable_compensation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='last_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='recruiter_score',
            field=models.IntegerField(blank=True, help_text='Score from 1 to 10', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', '🆕 New'), ('to_contact', '📲 To Contact'), ('contacted', '📧 Contacted'), ('interview', '📅 Interview Scheduled'), ('hired', '✅ Hired'), ('rejected', '❌ Rejected'), ('archived', '📦 Archived')], default='new', max_length=20),
        ),
    ]
