# Generated by Django 5.2.8 on 2025-12-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumemanager', '0003_application_assigned_to_application_last_contacted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagedetail',
            options={'ordering': ['language']},
        ),
        migrations.RemoveField(
            model_name='languagedetail',
            name='level',
        ),
        migrations.RemoveField(
            model_name='languagedetail',
            name='oral_level',
        ),
        migrations.RemoveField(
            model_name='languagedetail',
            name='phone_experience',
        ),
        migrations.RemoveField(
            model_name='languagedetail',
            name='written_level',
        ),
        migrations.AddField(
            model_name='languagedetail',
            name='global_level',
            field=models.CharField(choices=[('A1', 'A1 – Débutant'), ('A2', 'A2 – Élémentaire'), ('B1', 'B1 – Intermédiaire'), ('B2', 'B2 – Intermédiaire avancé'), ('C1', 'C1 – Avancé'), ('C2', 'C2 – Bilingue / Langue maternelle')], default='B1', max_length=20),
        ),
        migrations.AddField(
            model_name='languagedetail',
            name='listening_level',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('bon', 'Bon'), ('excellent', 'Excellent')], default='moyen', max_length=20),
        ),
        migrations.AddField(
            model_name='languagedetail',
            name='speaking_level',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('bon', 'Bon'), ('excellent', 'Excellent')], default='moyen', max_length=20),
        ),
        migrations.AddField(
            model_name='languagedetail',
            name='writing_level',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('bon', 'Bon'), ('excellent', 'Excellent')], default='moyen', max_length=20),
        ),
    ]
