# Generated by Django 5.2.8 on 2025-12-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumemanager', '0004_alter_languagedetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='download_speed',
            field=models.FloatField(blank=True, help_text='Download speed in Mbps', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='upload_speed',
            field=models.FloatField(blank=True, help_text='Upload speed in Mbps', null=True),
        ),
    ]
